import React, { useCallback, useEffect, useState } from 'react';
import Sidebar from '../components/Sidebar/Sidebar';
import Workspace from '../pages/Workspace/Workspace';
import UpdateModal, { UpdateInfo, UpdatePhase } from '../components/UpdateModal/UpdateModal';

// Wails-generated bindings — regenerated by `wails generate module`
import {
  CheckForUpdate,
  StartDownloadUpdate,
  ApplyUpdate,
} from '../../wailsjs/go/main/App';
import { EventsOn, EventsOff } from '../../wailsjs/runtime/runtime';

// ─── Types ────────────────────────────────────────────────────────────────────

interface UpdateStatus {
  phase: 'idle' | 'downloading' | 'done' | 'error';
  percent: number;
  errorMsg?: string;
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function MainLayout() {
  const [isEnvModalOpen, setIsEnvModalOpen] = useState(false);

  // ── Update state ──────────────────────────────────────────────────────────
  const [updateInfo, setUpdateInfo] = useState<UpdateInfo | null>(null);
  const [showUpdateModal, setShowUpdateModal] = useState(false);
  const [updatePhase, setUpdatePhase] = useState<UpdatePhase>('available');
  const [downloadPercent, setDownloadPercent] = useState(0);
  const [updateError, setUpdateError] = useState<string | undefined>(undefined);

  // ── Check for update on startup (delayed 3s to let app fully load) ────────
  useEffect(() => {
    const timer = setTimeout(async () => {
      try {
        const info = await CheckForUpdate();
        if (info) {
          setUpdateInfo(info as UpdateInfo);
          setUpdatePhase('available');
          setShowUpdateModal(true);
        }
      } catch (err) {
        // Non-fatal: silently log. App continues working normally.
        console.warn('[updater] update check failed (non-fatal):', err);
      }
    }, 3000);

    return () => clearTimeout(timer);
  }, []);

  // ── Listen to Go→JS progress events ──────────────────────────────────────
  useEffect(() => {
    const handler = (status: UpdateStatus) => {
      switch (status.phase) {
        case 'downloading':
          setUpdatePhase('downloading');
          setDownloadPercent(status.percent);
          break;
        case 'done':
          setUpdatePhase('done');
          setDownloadPercent(100);
          break;
        case 'error':
          setUpdatePhase('error');
          setUpdateError(status.errorMsg ?? 'Unknown error');
          break;
      }
    };

    EventsOn('updater:status', handler);
    return () => {
      EventsOff('updater:status');
    };
  }, []);

  // ── Handlers ──────────────────────────────────────────────────────────────

  const handleUpdateNow = useCallback(async () => {
    if (!updateInfo) return;

    if (updatePhase === 'available' || updatePhase === 'error') {
      // Start the download.
      setUpdatePhase('downloading');
      setDownloadPercent(0);
      setUpdateError(undefined);
      try {
        await StartDownloadUpdate(updateInfo.Version, updateInfo.URL, updateInfo.SHA256);
      } catch (err: any) {
        setUpdatePhase('error');
        setUpdateError(err?.message ?? String(err));
      }
      return;
    }

    if (updatePhase === 'done') {
      // Apply the update and quit.
      setUpdatePhase('applying');
      try {
        await ApplyUpdate();
      } catch (err: any) {
        setUpdatePhase('error');
        setUpdateError(err?.message ?? String(err));
      }
    }
  }, [updateInfo, updatePhase]);

  const handleLater = useCallback(() => {
    if (updatePhase !== 'downloading' && updatePhase !== 'applying') {
      setShowUpdateModal(false);
    }
  }, [updatePhase]);

  const handleClose = useCallback(() => {
    setShowUpdateModal(false);
    setUpdatePhase('available');
    setUpdateError(undefined);
  }, []);

  // ── Render ────────────────────────────────────────────────────────────────

  return (
    <div
      style={{
        display: 'flex',
        width: '100vw',
        height: '100vh',
        overflow: 'hidden',
        backgroundColor: 'var(--bg-app)',
        color: 'var(--text-main)',
        fontFamily: 'var(--font-sans)',
      }}
    >
      {/* Sidebar cố định bên trái (280px) */}
      <div
        style={{
          width: '280px',
          flexShrink: 0,
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
        }}
      >
        <Sidebar onOpenEnvModal={() => setIsEnvModalOpen(true)} />
      </div>

      {/* Vùng làm việc chính bên phải */}
      <div
        style={{
          flex: 1,
          height: '100%',
          overflow: 'hidden',
          display: 'flex',
          flexDirection: 'column',
        }}
      >
        <Workspace isEnvModalOpen={isEnvModalOpen} setIsEnvModalOpen={setIsEnvModalOpen} />
      </div>

      {/* Update Modal (portal-like, rendered last so it's on top) */}
      {showUpdateModal && updateInfo && (
        <UpdateModal
          updateInfo={updateInfo}
          phase={updatePhase}
          percent={downloadPercent}
          errorMsg={updateError}
          onUpdateNow={handleUpdateNow}
          onLater={handleLater}
          onClose={handleClose}
        />
      )}
    </div>
  );
}