// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CancelLoadTest() {
  return window['go']['main']['App']['CancelLoadTest']();
}

export function CancelStreamRequest(arg1) {
  return window['go']['main']['App']['CancelStreamRequest'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearMockServerLogs() {
  return window['go']['main']['App']['ClearMockServerLogs']();
}

export function CreateFolderInDB(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateFolderInDB'](arg1, arg2, arg3, arg4);
}

export function CreateProjectInDB(arg1, arg2) {
  return window['go']['main']['App']['CreateProjectInDB'](arg1, arg2);
}

export function CreateRequestInDB(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateRequestInDB'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteEnvironmentFromDB(arg1) {
  return window['go']['main']['App']['DeleteEnvironmentFromDB'](arg1);
}

export function DeleteFolderInDB(arg1) {
  return window['go']['main']['App']['DeleteFolderInDB'](arg1);
}

export function DeleteProjectInDB(arg1) {
  return window['go']['main']['App']['DeleteProjectInDB'](arg1);
}

export function DeleteRequestInDB(arg1) {
  return window['go']['main']['App']['DeleteRequestInDB'](arg1);
}

export function DeleteScenarioFromDB(arg1) {
  return window['go']['main']['App']['DeleteScenarioFromDB'](arg1);
}

export function DeleteUIScenario(arg1) {
  return window['go']['main']['App']['DeleteUIScenario'](arg1);
}

export function ExecuteLoadTest(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ExecuteLoadTest'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ExecuteRequest(arg1) {
  return window['go']['main']['App']['ExecuteRequest'](arg1);
}

export function ExecuteStreamRequest(arg1, arg2) {
  return window['go']['main']['App']['ExecuteStreamRequest'](arg1, arg2);
}

export function ExportFullWorkspace() {
  return window['go']['main']['App']['ExportFullWorkspace']();
}

export function GetAllProjectsData() {
  return window['go']['main']['App']['GetAllProjectsData']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetEnvironmentsFromDB() {
  return window['go']['main']['App']['GetEnvironmentsFromDB']();
}

export function GetMockServerStatus() {
  return window['go']['main']['App']['GetMockServerStatus']();
}

export function GetScenariosFromDB() {
  return window['go']['main']['App']['GetScenariosFromDB']();
}

export function GetScreenshotBase64(arg1) {
  return window['go']['main']['App']['GetScreenshotBase64'](arg1);
}

export function GetUIScenario(arg1) {
  return window['go']['main']['App']['GetUIScenario'](arg1);
}

export function GetUIScenarios() {
  return window['go']['main']['App']['GetUIScenarios']();
}

export function GetUITestResults(arg1) {
  return window['go']['main']['App']['GetUITestResults'](arg1);
}

export function GetUITestRuns(arg1) {
  return window['go']['main']['App']['GetUITestRuns'](arg1);
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function InstallPlaywrightBrowsers() {
  return window['go']['main']['App']['InstallPlaywrightBrowsers']();
}

export function RunUIScenario(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunUIScenario'](arg1, arg2, arg3);
}

export function SaveAllEnvironmentsToDB(arg1) {
  return window['go']['main']['App']['SaveAllEnvironmentsToDB'](arg1);
}

export function SaveEnvironmentToDB(arg1) {
  return window['go']['main']['App']['SaveEnvironmentToDB'](arg1);
}

export function SaveScenarioToDB(arg1) {
  return window['go']['main']['App']['SaveScenarioToDB'](arg1);
}

export function SaveUIScenario(arg1) {
  return window['go']['main']['App']['SaveUIScenario'](arg1);
}

export function StartDownloadUpdate(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartDownloadUpdate'](arg1, arg2, arg3);
}

export function StartMockServer(arg1, arg2) {
  return window['go']['main']['App']['StartMockServer'](arg1, arg2);
}

export function StopMockServer() {
  return window['go']['main']['App']['StopMockServer']();
}

export function StopUIScenario(arg1) {
  return window['go']['main']['App']['StopUIScenario'](arg1);
}

export function UpdateFolderInDB(arg1, arg2) {
  return window['go']['main']['App']['UpdateFolderInDB'](arg1, arg2);
}

export function UpdateMockRoutes(arg1) {
  return window['go']['main']['App']['UpdateMockRoutes'](arg1);
}

export function UpdateProjectInDB(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectInDB'](arg1, arg2);
}

export function UpdateRequestInDB(arg1) {
  return window['go']['main']['App']['UpdateRequestInDB'](arg1);
}
