// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CancelLoadTest() {
  return window['go']['main']['App']['CancelLoadTest']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CreateFolderInDB(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateFolderInDB'](arg1, arg2, arg3, arg4);
}

export function CreateProjectInDB(arg1, arg2) {
  return window['go']['main']['App']['CreateProjectInDB'](arg1, arg2);
}

export function CreateRequestInDB(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateRequestInDB'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteEnvironmentFromDB(arg1) {
  return window['go']['main']['App']['DeleteEnvironmentFromDB'](arg1);
}

export function DeleteFolderInDB(arg1) {
  return window['go']['main']['App']['DeleteFolderInDB'](arg1);
}

export function DeleteProjectInDB(arg1) {
  return window['go']['main']['App']['DeleteProjectInDB'](arg1);
}

export function DeleteRequestInDB(arg1) {
  return window['go']['main']['App']['DeleteRequestInDB'](arg1);
}

export function ExecuteLoadTest(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ExecuteLoadTest'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ExecuteRequest(arg1) {
  return window['go']['main']['App']['ExecuteRequest'](arg1);
}

export function ExportFullWorkspace() {
  return window['go']['main']['App']['ExportFullWorkspace']();
}

export function GetAllProjectsData() {
  return window['go']['main']['App']['GetAllProjectsData']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetEnvironmentsFromDB() {
  return window['go']['main']['App']['GetEnvironmentsFromDB']();
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function SaveAllEnvironmentsToDB(arg1) {
  return window['go']['main']['App']['SaveAllEnvironmentsToDB'](arg1);
}

export function SaveEnvironmentToDB(arg1) {
  return window['go']['main']['App']['SaveEnvironmentToDB'](arg1);
}

export function StartDownloadUpdate(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartDownloadUpdate'](arg1, arg2, arg3);
}

export function UpdateFolderInDB(arg1, arg2) {
  return window['go']['main']['App']['UpdateFolderInDB'](arg1, arg2);
}

export function UpdateProjectInDB(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectInDB'](arg1, arg2);
}

export function UpdateRequestInDB(arg1) {
  return window['go']['main']['App']['UpdateRequestInDB'](arg1);
}
