// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {core} from '../models';
import {main} from '../models';

export function ApplyUpdate():Promise<void>;

export function CancelLoadTest():Promise<void>;

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function CreateFolderInDB(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CreateProjectInDB(arg1:string,arg2:string):Promise<void>;

export function CreateRequestInDB(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function DeleteEnvironmentFromDB(arg1:string):Promise<void>;

export function DeleteFolderInDB(arg1:string):Promise<void>;

export function DeleteProjectInDB(arg1:string):Promise<void>;

export function DeleteRequestInDB(arg1:string):Promise<void>;

export function ExecuteLoadTest(arg1:core.RequestPayload,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number):Promise<core.StressTestResult>;

export function ExecuteRequest(arg1:core.RequestPayload):Promise<core.ResponsePayload>;

export function ExportFullWorkspace():Promise<string>;

export function GetAllProjectsData():Promise<main.ProjectDataPayload>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetEnvironmentsFromDB():Promise<Array<main.DBEnvironment>>;

export function GetUpdateStatus():Promise<main.UpdateStatus>;

export function SaveAllEnvironmentsToDB(arg1:Array<main.DBEnvironment>):Promise<void>;

export function SaveEnvironmentToDB(arg1:main.DBEnvironment):Promise<void>;

export function StartDownloadUpdate(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateFolderInDB(arg1:string,arg2:string):Promise<void>;

export function UpdateProjectInDB(arg1:string,arg2:string):Promise<void>;

export function UpdateRequestInDB(arg1:main.DBRequest):Promise<void>;
